# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [27]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

In [28]:
# Load the Food choices data set into a variable (e.g., df_food).

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [29]:
# Count by hand. (lol kidding)
df_food.shape

(125, 61)

What are the columns and their types in this data set?

In [30]:
# Show the column names and their types.
df_food.dtypes

GPA                  object
Gender                int64
breakfast             int64
calories_chicken      int64
calories_day        float64
                     ...
type_sports          object
veggies_day           int64
vitamins              int64
waffle_calories       int64
weight               object
Length: 61, dtype: object

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns?

In [31]:
# Remove 'em.
df_food = df_food[["calories_day", "weight", "Gender"]]
df_food.head()

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

What about `NaN`s? How many are there?

In [32]:
# Count 'em.
df_food.isna().sum()

calories_day    19
weight           2
Gender           0
dtype: int64

We gotta remove those `NaN`s―the entire row.

In [33]:
# Drop 'em.
df_food = df_food.dropna()
df_food.shape

(104, 3)

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [34]:
# Fix that.
df_food['calories_day'] = pd.to_numeric(df_food['calories_day'], errors='coerce')
df_food['weight'] = pd.to_numeric(df_food['weight'], errors='coerce')
df_food = df_food.dropna()
df_food.dtypes

calories_day    float64
weight          float64
Gender            int64
dtype: object

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [35]:
# Savey save!
df_food.head()

   calories_day  weight  Gender
1           3.0   155.0       1
4           2.0   190.0       1
5           3.0   190.0       1
6           3.0   180.0       2
7           3.0   137.0       1

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

In [36]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set into a variable (e.g., df_salary).
salary_path = '/Users/jacky/ds-fall-2026/Week-02-Pandas-and-How-to-Make-a-Sick-Project/data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv'
df_salary = pd.read_csv(salary_path, sep='	')
df_salary.head()

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

Was that hard? 🙃

#### rename the file to something that is better for all systems.  
* No spaces in filename (can use '_')
* all lower case

### Explore

You know the drill.

How much data did you just load?

In [37]:
# Count by hand. I'm dead serious.
df_salary.shape

(28062, 18)

What are the columns and their types?

In [38]:
# Show the column names and their types.
df_salary.dtypes

Timestamp                                                                                                                                                                                                                                object
How old are you?                                                                                                                                                                                                                         object
What industry do you work in?                                                                                                                                                                                                            object
Job title                                                                                                                                                                                                                                object
If your job title needs additional context, please clarify here:                                                                                                                                                                         object
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)     object
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                             object
If "Other," please indicate the currency here:                                                                                                                                                                                           object
If your income needs additional context, please provide it here:                                                                                                                                                                         object
What country do you work in?                                                                                                                                                                                                             object
If you're in the U.S., what state do you work in?                                                                                                                                                                                        object
What city do you work in?                                                                                                                                                                                                                object
How many years of professional work experience do you have overall?                                                                                                                                                                      object
How many years of professional work experience do you have in your field?                                                                                                                                                                object
What is your highest level of education completed?                                                                                                                                                                                       object
What is your gender?                                                                                                                                                                                                                     object
What is your race? (Choose all that apply.)                                                                                                                                                                                              object
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [39]:
# Rename 'em.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race
df_salary.columns = [
    'timestamp', 'age', 'industry', 'title', 'title_context',
    'salary', 'additional_compensation', 'currency', 'other_currency',
    'salary_context', 'country', 'state', 'city', 'total_yoe',
    'field_yoe', 'highest_education_completed', 'gender', 'race'
]
df_salary = df_salary.rename(columns={df_salary.columns[i]: col for i, col in enumerate(df_salary.columns)})
df_salary.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [40]:
# List the unique industries and a count of their instances.
df_salary['industry'].value_counts()

industry
Computing or Tech                          4699
Education (Higher Education)               2464
Nonprofits                                 2419
Health care                                1896
Government and Public Administration       1889
                                           ...
Gaming (Gambling)                             1
Regulatory Affairs- nutraceuticals            1
Manufacturing : corporate admin support       1
Real Estate Investment Support                1
Wine & Spirits                                1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new dataframe.

In [41]:
# Filtery filter. (Save it to a new variable, df_salary_tech.)
top_ind = df_salary['industry'].value_counts().index[0]
df_salary_tech = df_salary[df_salary['industry'] == top_ind].copy()
df_salary_tech.shape

(4699, 18)

Do a sanity check to make sure that the only values you kept are the one you are filtered for.

In [42]:
# Sanity Check 
df_salary_tech['industry'].unique()

array(['Computing or Tech'], dtype=object)

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [18]:
# Filtery filter for just the jobs that pay in USD!
df_salary_tech = df_salary_tech[df_salary_tech['currency'] == 'USD']
df_salary_tech.shape

(3777, 18)

What we really want know is how each U.S. city pays in tech. What value in `country` represents the United States of America?

In [19]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_salary_tech['country'].value_counts()

country
United States               1576
USA                         1222
US                           412
U.S.                         108
United States of America      90
                            ...
Pakistan                       1
Puerto Rico                    1
America                        1
Uniyed states                  1
Burma                          1
Name: count, Length: 76, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [20]:
# Replace them all with 'US'.
top5 = df_salary_tech['country'].value_counts().nlargest(5).index.tolist()
df_salary_tech.loc[:, 'country'] = df_salary_tech['country'].replace(top5, 'US')

Have a look at the count of each unique country again now.

In [21]:
# Count again.
df_salary_tech['country'].value_counts()

country
US                3408
United States       68
Usa                 59
USA                 56
usa                 28
                  ...
Mexico               1
United Stateds       1
ISA                  1
singapore            1
Burma                1
Name: count, Length: 72, dtype: int64

Did you notice anything interesting?

In [ ]:
# BONUS CREDIT: resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [ ]:

# BONUS CREDIT: if you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [22]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
df_salary_tech['salary_clean'] = pd.to_numeric(df_salary_tech['salary'].astype(str).str.replace('[^0-9.]','', regex=True), errors='coerce')
grouped = df_salary_tech.groupby('state')['salary_clean'].agg(['min','mean','max']).sort_values('mean', ascending=False)
grouped.head()

                                min           mean      max
state
Michigan, Texas, Washington  340000  340000.000000   340000
California, Oregon           200000  200000.000000   200000
California, Colorado         176000  176000.000000   176000
Georgia, Massachusetts       175000  175000.000000   175000
Florida                       28800  157457.232143  2600000

Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed.

In [23]:
# Fix it.
df_salary_tech['salary_clean'] = pd.to_numeric(df_salary_tech['salary'].astype(str).str.replace('[^0-9.]','', regex=True), errors='coerce')
df_salary_tech = df_salary_tech.dropna(subset=['salary_clean'])
df_salary_tech.shape

(3777, 19)

Let’s try that again.

In [24]:
# Try it again. Yeah!
df_salary_tech.groupby('state')['salary_clean'].agg(['min','mean','max']).sort_values('mean', ascending=False).head()

                                min           mean      max
state
Michigan, Texas, Washington  340000  340000.000000   340000
California, Oregon           200000  200000.000000   200000
California, Colorado         176000  176000.000000   176000
Georgia, Massachusetts       175000  175000.000000   175000
Florida                       28800  157457.232143  2600000

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [25]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.
df_salary_tech['timestamp'] = pd.to_datetime(df_salary_tech['timestamp'], errors='coerce')
df_recent = df_salary_tech[df_salary_tech['timestamp'].dt.year.isin([2021,2022,2023])].copy()
df_recent.groupby('state')['salary_clean'].agg(['min','mean','max']).sort_values('mean', ascending=False).head()

                                  min      mean     max
state
Michigan, Texas, Washington    340000  340000.0  340000
California, Oregon             200000  200000.0  200000
California, Colorado           176000  176000.0  176000
Georgia, Massachusetts         175000  175000.0  175000
Alabama, District of Columbia  156000  156000.0  156000

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)